# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    - script: |
    sudo apt install mono-devel.
    sudo apt intall mono-complete
    sudo apt-get install unzip
    wget "https://github.com/dotnet/docfx/releases/download/v2.43.1/docfx.zip" 
    unzip docfx.zip
    
    
  displayName: 'Run a multi-line script'

- script: echo Install mono Dev!

- script: |
    - script: |
    ls -la
    mono docfx.exe build docfx_project/docfx.json
    
  displayName: 'Run a multi-line install mono'